version: "0.1"

services:
  eureka-server:
    image: markhong93/eureka-server
    networks:
      - test-net
    ports:
      - 8761:80
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server/eureka

  gateway-server:
    image: markhong93/gateway-server
    networks:
      - test-net
    ports:
      - 8080:80
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server/eureka
    depends_on:
      - eureka-server

  user-server:
    image: markhong93/user-server
    networks:
      - test-net
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server/eureka
    depends_on:
      - eureka-server

  board-server:
    image: markhong93/board-server
    networks:
      - test-net
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server/eureka
    depends_on:
      - eureka-server

networks:
  test-net: