spring:
  application:
    name: user-server
  datasource:
    # local
#    url: r2dbc:mariadb://localhost:3306/boilerplate
    # docker
    url: r2dbc:mariadb://host.docker.internal:3306/boilerplate
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  # local
#  port: 0
  # docker
  port: 80

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # local
#      defaultZone: http://localhost:8761/eureka
      # docker
      defaultZone: http://eureka-server/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, shutdown
  endpoint:
    shutdown:
      enabled: true