server:
  port: 80

spring:
  application:
    name: api-repository
  
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  sql:
    init:
      platform: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Swagger
management:
  endpoint:
    web:
      exposure:
        include: "*"
        exclude: env, beans


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
    # local
#      defaultZone: http://localhost:8761/eureka
    # docker
      defaultZone: http://eureka-server/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}

        