server:
  # local
#  port: ${service_port:8080}
  # docker
  port: ${service_port:80}

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
    # local
#      defaultZone: http://localhost:8761/eureka
    # docker
      defaultZone: http://eureka-server/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      enabled: true
    shutdown:
      enabled: true
