spring:
  application:
    name: eureka-server

server:
  # local
#  port: ${service_port:8761}
  # docker
  port: ${service_port:80}

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, shutdown
      endpoint:
        shutdown:
          enabled: true
# Uncomment if you'd rather use multi-peer Eureka with the eureka-1 and eureka-2
# profiles below
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://${other.eureka.host}:${other.eureka.port}/eureka

#---
#spring:
#  profiles: eureka-1
#  application:
#    name: eureka-1

#server:
#  port: 8761

#eureka:
#  instance:
#    hostname: eureka.chunjae.com

